name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - "papers/**"
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "papers/**"
      - "README.md"
  workflow_dispatch:

env:
  AGDA_BRANCH: v2.8.0
  CUBICAL_BRANCH: v0.9
  GHC_VERSION: 9.10.2
  CACHE_PATHS: |
    ~/cubical/_build
    ~/symmetries/_build

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Restore external dependencies cache
        uses: actions/cache/restore@v3
        id: cache-external-restore
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ runner.os }}-${{ env.AGDA_BRANCH }}-${{ env.CUBICAL_BRANCH }}

      ########################################################################
      ## INSTALLATION STEPS
      ########################################################################

      - name: Download and install Agda from github
        run: |
          mkdir /tmp/agda/
          cd /tmp/agda/
          wget -O Agda.tar.xz https://github.com/agda/agda/releases/download/${{ env.AGDA_BRANCH }}/Agda-${{ env.AGDA_BRANCH }}-linux.tar.xz
          tar -xf Agda.tar.xz
          chmod +x ./agda
          ./agda --version
          pwd >> $GITHUB_PATH

      - name: Download and install the cubical library from github
        run: |
          git clone https://github.com/agda/cubical --branch ${{ env.CUBICAL_BRANCH }} --depth=1
          cd cubical
          agda --build-library
          mkdir -p ~/.agda
          echo "$GITHUB_WORKSPACE/cubical/cubical.agda-lib" >> ~/.agda/libraries

      - name: Save external dependencies cache
        uses: actions/cache/save@v3
        id: cache-external-save
        with:
          path: ${{ env.CACHE_PATHS }}
          key: ${{ steps.cache-external-restore.outputs.cache-primary-key }}

      ########################################################################
      ## CHECKOUT
      ########################################################################

      # By default github actions do not pull the repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: symmetries

      ########################################################################
      ## TESTING
      ########################################################################

      - name: Generate everything.agda
        run: |
          cd symmetries
          chmod +x create-everything.sh
          ./create-everything.sh

      - name: Test
        run: |
          cd symmetries
          agda --build-library
