name: ci
on:
  push:
    branches:
      - main
    paths-ignore:
      - "papers/**"
      - "README.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "papers/**"
      - "README.md"
  workflow_dispatch:

env:
  AGDA_BRANCH: v2.8.0
  CUBICAL_BRANCH: v0.9
  GHC_VERSION: 9.10.2

jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - name: Cache Agda artifacts
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-${{ env.AGDA_BRANCH }}-${{ env.CUBICAL_BRANCH }}
          path: |
            ${{ github.workspace }}/cubical/_build
            ${{ github.workspace }}/symmetries/_build

      ########################################################################
      ## INSTALLATION STEPS
      ########################################################################

      - name: Download and install Agda from github
        run: |
          mkdir /tmp/agda/
          cd /tmp/agda/
          wget -O Agda.tar.xz https://github.com/agda/agda/releases/download/${{ env.AGDA_BRANCH }}/Agda-${{ env.AGDA_BRANCH }}-linux.tar.xz
          tar -xf Agda.tar.xz
          chmod +x ./agda
          ./agda --version
          pwd >> $GITHUB_PATH

      - name: Download and install the cubical library from github
        run: |
          git clone https://github.com/agda/cubical --branch ${{ env.CUBICAL_BRANCH }} --depth=1
          cd cubical
          agda --build-library
          mkdir -p ~/.agda
          echo "$GITHUB_WORKSPACE/cubical/cubical.agda-lib" >> ~/.agda/libraries

      ########################################################################
      ## CHECKOUT
      ########################################################################

      # By default github actions do not pull the repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: symmetries

      ########################################################################
      ## TESTING
      ########################################################################

      - name: Generate everything.agda
        run: |
          cd symmetries
          chmod +x create-everything.sh
          ./create-everything.sh

      - name: Build library
        run: |
          cd symmetries
          agda --build-library

      ########################################################################
      ## HTML PAGE
      ########################################################################

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build html
        run: |
          cd symmetries
          agda --html --html-dir=public --highlight-occurrences index.agda
          cp Agda.css public/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'symmetries/public'